# Generated by Django 5.2.7 on 2025-10-21 20:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_protein', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_carbs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_fat', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.FloatField(blank=True, help_text='gram', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(blank=True, help_text='gram', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.FloatField(blank=True, help_text='gram', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.FloatField(blank=True, help_text='gram', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.FloatField(blank=True, help_text='gram', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('snack', 'Atıştırmalık'), ('beverage', 'İçecek'), ('fruit', 'Meyve'), ('vegetable', 'Sebze'), ('protein', 'Protein'), ('carb', 'Karbonhidrat'), ('fat', 'Yağ')], default='snack', max_length=20)),
                ('serving_size', models.CharField(default='100g', help_text='Porsiyon boyutu', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomPlanFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('meal_time', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('snack', 'Atıştırmalık')], default='snack', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sıralama')),
                ('custom_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_foods', to='users.customplan')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.food')),
            ],
            options={
                'ordering': ['order', 'meal_time'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Miktar', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('calories', models.FloatField(help_text='Hesaplanan kalori', validators=[django.core.validators.MinValueValidator(0)])),
                ('meal_time', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('snack', 'Atıştırmalık')], default='snack', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Ek notlar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='users.dailyintake')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.food')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.FloatField(help_text='kg', validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)])),
                ('height', models.FloatField(help_text='cm', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(250.0)])),
                ('goal', models.CharField(choices=[('lose_weight', 'Kilo Vermek'), ('gain_weight', 'Kilo Almak'), ('healthy_eating', 'Sağlıklı Beslenmek'), ('athlete', 'Sporcu'), ('maintain', 'Kilo Korumak')], default='healthy_eating', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Hareketsiz'), ('light', 'Hafif Aktif'), ('moderate', 'Orta Aktif'), ('active', 'Aktif'), ('very_active', 'Çok Aktif')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_score', models.FloatField(blank=True, help_text='OCR güven skoru', null=True)),
                ('image_path', models.CharField(blank=True, help_text='Taranan görsel yolu', max_length=500, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='AI tarafından işlendi mi?')),
                ('ai_suggestion', models.TextField(blank=True, help_text='AI önerisi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_foods', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_intakes', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='customplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_plans', to='users.userprofile'),
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('interaction_type', models.CharField(choices=[('general', 'Genel Sohbet'), ('nutrition_advice', 'Beslenme Önerisi'), ('meal_planning', 'Öğün Planlama'), ('motivation', 'Motivasyon'), ('question', 'Soru')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyintake',
            unique_together={('user', 'date')},
        ),
    ]
